/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/hex108/cron-hpa-controller/pkg/apis/cronhpacontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCronHPAs implements CronHPAInterface
type FakeCronHPAs struct {
	Fake *FakeCronhpacontrollerV1alpha1
	ns   string
}

var cronhpasResource = schema.GroupVersionResource{Group: "cronhpacontroller.gs.io", Version: "v1alpha1", Resource: "cronhpas"}

var cronhpasKind = schema.GroupVersionKind{Group: "cronhpacontroller.gs.io", Version: "v1alpha1", Kind: "CronHPA"}

// Get takes name of the cronHPA, and returns the corresponding cronHPA object, and an error if there is any.
func (c *FakeCronHPAs) Get(name string, options v1.GetOptions) (result *v1alpha1.CronHPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cronhpasResource, c.ns, name), &v1alpha1.CronHPA{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CronHPA), err
}

// List takes label and field selectors, and returns the list of CronHPAs that match those selectors.
func (c *FakeCronHPAs) List(opts v1.ListOptions) (result *v1alpha1.CronHPAList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cronhpasResource, cronhpasKind, c.ns, opts), &v1alpha1.CronHPAList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CronHPAList{ListMeta: obj.(*v1alpha1.CronHPAList).ListMeta}
	for _, item := range obj.(*v1alpha1.CronHPAList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cronHPAs.
func (c *FakeCronHPAs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cronhpasResource, c.ns, opts))

}

// Create takes the representation of a cronHPA and creates it.  Returns the server's representation of the cronHPA, and an error, if there is any.
func (c *FakeCronHPAs) Create(cronHPA *v1alpha1.CronHPA) (result *v1alpha1.CronHPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cronhpasResource, c.ns, cronHPA), &v1alpha1.CronHPA{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CronHPA), err
}

// Update takes the representation of a cronHPA and updates it. Returns the server's representation of the cronHPA, and an error, if there is any.
func (c *FakeCronHPAs) Update(cronHPA *v1alpha1.CronHPA) (result *v1alpha1.CronHPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cronhpasResource, c.ns, cronHPA), &v1alpha1.CronHPA{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CronHPA), err
}

// Delete takes name of the cronHPA and deletes it. Returns an error if one occurs.
func (c *FakeCronHPAs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cronhpasResource, c.ns, name), &v1alpha1.CronHPA{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCronHPAs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cronhpasResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CronHPAList{})
	return err
}

// Patch applies the patch and returns the patched cronHPA.
func (c *FakeCronHPAs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CronHPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cronhpasResource, c.ns, name, pt, data, subresources...), &v1alpha1.CronHPA{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CronHPA), err
}
